In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../dataset/raw/spam.csv", encoding="ISO-8859-1")

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   str
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: str(5)
memory usage: 217.8 KB

In [7]:
df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)

In [8]:
df.sample()

      v1                                                 v2
103  ham  wow. You're right! I didn't mean to do that. I...

In [9]:
#renaming the column
df.rename(columns={'v1':'target','v2':'text'},inplace=True)

In [10]:
df.sample()

     target                                               text
3562   spam  Auction round 4. The highest bid is now å£54. ...

In [15]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [16]:
df['target'] = encoder.fit_transform(df['target'])
df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [18]:
df.isnull().sum()

target    0
text      0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(403)

In [21]:
df = df.drop_duplicates(keep="first")

In [22]:
df.duplicated().sum()

np.int64(0)

In [24]:
# Save as a standard, readable CSV
df.to_csv('../dataset/processed/spam_cleaned.csv', index=False)